# Generated by Django 5.2.8 on 2025-11-14 17:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_uz', models.CharField(max_length=200, null=True)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('value', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('unit_uz', models.CharField(max_length=50, null=True)),
                ('unit_ru', models.CharField(max_length=50, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='indicators/')),
                ('order', models.IntegerField(default=0)),
                ('year', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PowerPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_uz', models.CharField(max_length=200, null=True)),
                ('name_ru', models.CharField(max_length=200, null=True)),
                ('plant_type', models.CharField(choices=[('TPS', 'Thermal Power Station'), ('TPC', 'Thermal Power Central'), ('HPP', 'Hydro Power Plant')], max_length=3)),
                ('capacity', models.IntegerField(help_text='Capacity in MW')),
                ('location', models.CharField(max_length=200)),
                ('location_uz', models.CharField(max_length=200, null=True)),
                ('location_ru', models.CharField(max_length=200, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, default=41.0, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=69.0, max_digits=9)),
                ('description', ckeditor.fields.RichTextField()),
                ('description_uz', ckeditor.fields.RichTextField(null=True)),
                ('description_ru', ckeditor.fields.RichTextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='powerplants/')),
                ('established_year', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
